#!/bin/bash

DOCKER_BUILDKIT=${DOCKER_BUILDKIT} docker build -f projector-docker/Dockerfile -t ${IMAGE_NAME} --build-arg buildGradle=true --build-arg downloadUrl=${downloadPrefix}/${SOURCE_BRANCH}.tar.gz .
